---
- hosts: all
  become: true
  tasks:
   - name: Make sure the packages openssh and openssl are up to date.
     ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
     loop:
      - openssh
      - openssl
     ignore_errors: yes
   - name: Check if docker is installed
     ansible.builtin.command: docker --version
     register: docker_command_output
     ignore_errors: yes
   - name: Install docker
     ansible.builtin.apt:
      name: docker.io
      state: present
     when:
      docker_command_output.failed 
